#! /bin/sh

xrandr --output eDP1 --auto --output DP1 --auto --right-of eDP1 
xrandr --output eDP1 --auto --output HDMI1 --auto --right-of eDP1 
xset -b 
feh --bg-fill /home/sheng/Pictures/wallhaven-84327.jpg
xrdb -merge ~/.Xresources
xset +fp ~/.fonts && xset +fp /usr/share/fonts/local
xset fp rehash
wmname LG3D

# Visual options

bspc config border_width        4
bspc config window_gap         12

bspc config top_padding 24
bspc config split_ratio 0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true

bspc config normal_border_color "#2b303b"
bspc config active_border_color "#96b5b4"
bspc config focused_border_color "#8fa1b3" 
bspc config presel_border_color "#bf616a"
bspc config urgent_border_color "#b48ead"
bspc config focused_locked_border_color "#ebcb8b"

bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc monitor eDP1 -d one two three four five
bspc monitor DP1 -d six seven eight nine ten

panel &
