#! /bin/bash

nrows=4																#number of rows of desks
npeopleperrow="5:5:6:8"												#number of people in each rows

total=$(echo $npeopleperrow | sed -e 's/:/+/g' | bc)				#sum of the number of people
seat=$(((RANDOM % total) + 1)) 
echo "total:"$total 
echo "seat:"$seat

count=1
while [ $count -le $nrows ]; do  									#splitting up each row into row[index]
	row[$count]=$(echo $npeopleperrow | cut -d: -f$count)
	count=$((count+1))2
done

rowcounter=1
rowsum=0
while [ $rowcounter -le $nrows ]; do
	rowsum=$((rowsum + row[$rowcounter]))
	if [ $seat -le $rowsum ]
		then
			echo "row:" $rowcounter
			echo "column: " $((seat - rowsum + row[$rowcounter]))   #seat - previous rowsum = column
			break
	fi
	rowcounter=$((rowcounter + 1))
done
